spring:
  application:
    name: booking-service

  profiles:
    active: dev

  resilience4j:
    circuitbreaker:
      instances:
        paymentService:
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          slidingWindowSize: 10
          waitDurationInOpenState: 10s
  config:
    import: optional:configserver:http://config-server:8888
